### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [styrke10/skraafotos#1]
Please update plugin homepage link in  metadata.txt to refer to page dedicated to the plugin. If you do not have one just use the repo as the link

**Comment by styrke10** [comment]
Hi,

 

I have now updated the metadata as per your request!

 

Best regards,

Morten

 

--

Morten Storm

Styrke 10 ApS



House of Innovation | Jernbanegade 27 | 6000 Kolding | Denmark

 

www:  <https://styrke10.dk> https://styrke10.dk

mobile: +45 51 51 09 29

 



 

Fra: mazano ***@***.***> 
Sendt: 18. april 2024 09:01
Til: styrke10/skraafotos ***@***.***>
Cc: Subscribed ***@***.***>
Emne: [styrke10/skraafotos] Plugin approval (Issue #1)

 

Please update plugin homepage link in metadata.txt to refer to page dedicated to the plugin. If you do not have one just use the repo as the link
